# This file may be used to create a conda environment using:
# $ conda create --name openLapSim --file <this file>

name: openLapSim
dependencies:
- python=3.6
- cython
- h5py
- jupyter
- matplotlib
- numpy
- psutil
- scipy

- pip:
  - mpi4py
  - terminaltables
  - tqdm
  - jsonpickle
